### ISSUE TITLE
Add Windows development part

### ISSUE THREAD

**Issue by unintendedbear** [MusesProject/Muses-Developer-Guide#9]
New section about how to run MUSES on Windows and how to develop for the Windows part.

**Comment by JJ** [comment]
Just one phrase: erase Windows, install Linux, and follow instructions for
Linux.

2015-05-18 15:58 GMT+02:00 Paloma de las Cuevas Delgado <
notifications@github.com>:

> New section about how to run MUSES on Windows and how to develop for the
> Windows part.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MusesProject/Muses-Developer-Guide/issues/9.

## 

JJ

**Comment by jmseigneur** [comment]
Where is the Like?... ah yes... forgot I'm on Windows ;-)

On Monday, May 18, 2015, Juan Julián Merelo Guervós <
notifications@github.com> wrote:

> Just one phrase: erase Windows, install Linux, and follow instructions for
> Linux.
> 
> 2015-05-18 15:58 GMT+02:00 Paloma de las Cuevas Delgado <
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>:
> 
> > New section about how to run MUSES on Windows and how to develop for the
> > Windows part.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/MusesProject/Muses-Developer-Guide/issues/9.
> 
> ## 
> 
> JJ
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MusesProject/Muses-Developer-Guide/issues/9#issuecomment-103071381
> .

## 

LEGAL NOTICE
This message (including all attachments) contains confidential information
intended for a specific individual and purpose, and is protected by law.
Any confidentiality or privilege is not waived or lost because this email
has been sent to you by mistake. If you have received it in error, please
let us know by reply email, delete it from your system and destroy any
copies.

This email is also subject to copyright. Any disclosure, copying, or
distribution of this message, or the taking of any action based on it, is
strictly prohibited.

Emails may be interfered with, may contain computer viruses or other
defects and may not be successfully replicated on other systems. We give no
warranties in relation to these matters. If you have any doubts about the
authenticity of an email purportedly sent by us, please contact us
immediately.
